GEMINI_API_KEY = "AIzaSyDGxW0c14UZd8TOPn1xpJK4vTVQpCfWZj4"

# MySQL Railway
[mysql]
host = "cabOOSE.proxy.rlwy.net"
port = 47488
database = "railway"
user = "root"
password = "htlpYrDeHTlriVTkLHdMQPlbVdmQpqBQ"
